GuitarsAreCool/Models/ErrorViewModel.cs
using System;

namespace GuitarsAreCool.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GuitarsAreCool/Models/Guitar.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GuitarsAreCool
{
    /// <summary>
    /// Represents a single guitar
    /// </summary>
    public class Guitar
    {
        /// <summary>
        /// Unique identifier for each individual guitar
        /// Serial Number
        /// </summary>
        public int GuitarId { get; set; }

        [Required(ErrorMessage = "Who made your guitar?")]
        /// <summary>
        /// The make of the guitar
        /// Example: Gibson
        /// </summary>
        public string Brand { get; set; }

        /// <summary>
        /// The model of the guitar
        /// Example: Les Paul Standard
        /// </summary>
        public string Style { get; set; }



    }
}

GuitarsAreCool/Controllers/GuitarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Server.IIS.Core;

namespace GuitarsAreCool.Controllers
{
    public class GuitarController : Controller
    {
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(IFormCollection form)
        {
            Guitar guitar = new Guitar();
            guitar.Brand = form["guitar"];
            guitar.Style = form["style"];

            //Add to DataBase

            ViewData["Added"] = true;

            return View();
        }

        [HttpGet]
        public IActionResult AddWithBinding()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddWithBinding(Guitar guitar)
        {
            if (ModelState.IsValid)
            {
                ViewData["Message"] = $"{guitar.Brand} {guitar.Style} was added!"; 
                // Add to Db HERE!!
            }
            return View();
        }
    }
}

GuitarsAreCool/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using GuitarsAreCool.Models;

namespace GuitarsAreCool.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GuitarsAreCool/Views/Guitar/Add.cshtml
@{
    ViewData["Title"] = "Add new Guitar";
}



@if (ViewData["Added"] == null)
{
    <h1>Add new Guitar</h1>

    <form method="post">
        <label>Brand</label>
        <input type="text" name="brand" />
        <br />

        <label>Style</label>
        <input type="text" name="style" />
        <br />

        <input type="submit" value="Add Guitar" />
    </form>

}
else
{
<p>Guitar Added!!</p>
}

GuitarsAreCool/Views/Guitar/AddWithBinding.cshtml
@model Guitar;
@{
    ViewData["Title"] = "AddWithBinding";
}

<h1>Add with ModelBinding</h1>

@if (ViewData["Message"] == null)
{
    <form method="post">
        <label asp-for="Brand"></label>
        <input asp-for="Brand" class="form-control" />
        <span asp-validation-for="Brand"></span>
        <br />

        <label asp-for="Style"></label>
        <input asp-for="Style" class="form-control" />
        <span asp-validation-for="Style"></span>
        <br />

        <input type="submit" value="Add Guitar" />
    </form>
}
else
{
    <h2>@ViewData["Message"]</h2>
}

@section Scripts
{
   <partial name="_ValidationScriptsPartial" />
}

GuitarsAreCool/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

GuitarsAreCool/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GuitarsAreCool</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GuitarsAreCool</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Guitar"
                               asp-action="Add">Add a Guitar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Guitar"
                               asp-action="Add">Add a Guitar with ModelBinding</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - GuitarsAreCool - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>